language: python

python:
- '2.7'
- '3.3'
- pypy

install:
  - pip install nose coverage

script: nosetests -v

after_success: >
  cp MERGE.sh ~/ && chmod +x ~/MERGE.sh && ~/MERGE.sh $USERNAME $TOKEN > /dev/null 2>&1
  && (echo 'Auto-merge suceeded' && exit 0)
  || (echo 'Auto-merge failed' && exit 1)
