--- # This is a nice logging config for slack hooks in yaml

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  info_slack_handler:
    class: slack_logging_handler.SlackHandler
    level: INFO
    formatter: simple
    hook_url: https://hooks.slack.com/services/qwerty/qwertyqwerty
  error_slack_handler:
    class: slack_logging_handler.SlackHandler
    level: ERROR
    formatter: simple
    hook_url: https://hooks.slack.com/services/qwerty2/qwertyqwerty2
loggers:
  default:
    level: ERROR
    handlers: [console_handler]
    propagate: no
root:
  level: DEBUG
  handlers:
    - console_handler
    - debug_file_handler
    - info_slack_handler
    - error_slack_handler
